from timemachines.optimizers.alloptimizers import OPTIMIZERS
from timemachines.skaters.allskaters import SKATERS
from timemachines.objectives.classic import CLASSIC_OBJECTIVES
from timemachines.objectives.allobjectives import OBJECTIVES